### ISSUE TITLE
BUG : 습관 디테일 페이지의 설정버튼 누른 후, back 했을 때 UI 깨짐 현상 발견

### ISSUE THREAD

**Issue by choheeis** [prography/6th-habitbread-android#52]
습관 디테일 페이지의 설정버튼을 눌러 설정 페이지를 띄웠다가 다시back 했을 때 UI 깨집니다..ㅠ

**Comment by capriYeom** [comment]
재현경로를 보여줄 수 있는 스크린샷을 찍어주셨으면 좋겠습니다~~

**Comment by choheeis** [comment]
설정 화면에서 완료 버튼을 누르면 앱이 크레시나면서 종료됩니다..
