### ISSUE TITLE
BUG: 랭킹 탭에서 모든 유저의 순위가 나오지 않습니다.  

### ISSUE THREAD

**Issue by harrywinks** [prography/6th-habitbread-android#57]
더 구체적으로 쓰자면, 제가 474등인데 제 순위가 랭킹 탭의 리사이클러뷰상에서 보이지 않습니다.

**Comment by capriYeom** [comment]
지금 저희의 상황이 200등까지 보이도록 설정을 했습니다. 현재 200등 이하의 순위는 보이지 않으며, 자신의 등수가 그 이하일 때 확인을 하는 방법은 상단에 보이는 자신을 등수를 확인하는 방법밖에 없습니다.
